services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: gobank
      POSTGRES_PASSWORD: gobank
      POSTGRES_DB: gobank
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./person/internal/core/sdk/ddl:/docker-entrypoint-initdb.d
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  pg_data:
