@path = localhost:3000

GET http://{{path}}/v1/health
Content-Type: application/json

###
POST http://{{path}}/v1/person
Content-Type: application/json

{
  "name": "Vinicius Barbosa",
  "document": "1231231231222"
}


###
GET http://{{path}}/v1/person/01910f6d-5f5d-7824-a640-8483af1b0709
Content-Type: application/json
